name: TradeShop
version: ${project.version}
main: org.shanerx.tradeshop.TradeShop
api-version: 1.14
load: POSTWORLD

authors: [ Lori00, KillerOfPie ]
description: ${project.description}
website: ${project.url}

commands:
  tradeshop:
    description: Core command for TradeShop
    aliases: [ ts ]
